### PR TITLE
Refactor into BaseScanner

### PR DESCRIPTION
**Pull request by traviscrawford**
Initially this project started as a Spark SQL data source, and over time has
added an RDD-based scanner too. Here we refactor the common scanner parts into
`BaseScanner` so they can more easily be shared.

### CODE REVIEW

**Comment by traviscrawford** [comment]
@sboora Can you take a look at this? If this looks good I'll merge and publish a new release that includes your changes too.

**Comment by sboora** [comment]
We can probably move the `scan` method to `BaseScanner` as well.

**Comment by traviscrawford** [comment]
Those are different, actually. One returns rows and the other strings. Maybe we can see if there are opportunities to reuse scan code as a future change?

**Comment by sboora** [comment]
LGTM!

**Comment by sboora** [comment]
ah, did not notice that.

**Pull request merged**
